---
- name: Install and Configure Zabbix Agent 2 on Windows Hosts
  hosts: all
  gather_facts: no
  vars:
    zabbix_server_ip: "172.16.42.143"  # Replace with your Zabbix server IP
    zabbix_agent_port: "10050"
    zabbix_agent_version: "7.2.2"      # Specify desired version

  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present
      register: choco_install
      retries: 3
      delay: 5
      until: choco_install is success
      ignore_errors: yes

    - name: Install Zabbix Agent 2 using Chocolatey
      win_chocolatey:
        name: zabbix-agent
        version: "{{ zabbix_agent_version }}"
        state: present
        package_params: "/SERVER={{ zabbix_server_ip }} /PORT={{ zabbix_agent_port }}"
      register: zabbix_install
      retries: 3
      delay: 5
      until: zabbix_install is success
      ignore_errors: yes

    - name: Ensure Zabbix Agent 2 service is running
      win_service:
        name: "Zabbix Agent 2"
        state: started
        start_mode: auto
      register: service_status
      retries: 3
      delay: 5
      until: service_status is success
      ignore_errors: yes

    - name: Verify Zabbix Agent 2 installation
      win_stat:
        path: "C:\\Program Files\\Zabbix Agent 2\\zabbix_agent2.exe"
      register: zabbix_path
      failed_when: not zabbix_path.stat.exists
      ignore_errors: yes

    - name: Debug installation status
      ansible.builtin.debug:
        msg: "Zabbix Agent 2 installation {{ 'succeeded' if zabbix_path.stat.exists else 'failed' }}"
