---
- name: Install Firefox on Windows Hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present
      register: choco_install
      retries: 3
      delay: 5
      until: choco_install is success
      ignore_errors: yes

    - name: Install Firefox using Chocolatey
      win_chocolatey:
        name: firefox
        state: present
      register: firefox_install
      retries: 3
      delay: 5
      until: firefox_install is success
      ignore_errors: yes

    - name: Verify Firefox installation
      win_stat:
        path: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
      register: firefox_path
      failed_when: not firefox_path.stat.exists
      ignore_errors: yes

    - name: Debug installation status
      ansible.builtin.debug:
        msg: "Firefox installation {{ 'succeeded' if firefox_path.stat.exists else 'failed' }}"
