---
- name: Install and configure Zabbix Agent 2 on Rocky Linux
  hosts: all
  become: yes
  become_method: root
  vars:
    zabbix_agent2_hostname: "{{ ansible_hostname }}"

  tasks:
    - name: Ensure system is updated
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes

        
    - name: Install prerequisites
      ansible.builtin.yum:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Install Zabbix 7.2 repository
      ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/7.2/release/rocky/9/noarch/zabbix-release-latest-7.2.el9.noarch.rpm
        state: present
        disable_gpg_check: yes 

    - name: Update YUM cache
      ansible.builtin.yum:
        update_cache: yes

    - name: Install Zabbix Agent 2
      ansible.builtin.yum:
        name: zabbix-agent2
        state: latest

    - name: Configure Server address
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^#?Server='
        line: "Server={{ zabbix_server }}"
        state: present
      notify: Restart Zabbix Agent2

    - name: Configure ServerActive address
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^#?ServerActive='
        line: "ServerActive={{ zabbix_server_active }}"
        state: present
      notify: Restart Zabbix Agent2

    - name: Configure Hostname
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^#?Hostname='
        line: "Hostname={{ zabbix_agent2_hostname }}"
        state: present
      notify: Restart Zabbix Agent2

    - name: Enable and start Zabbix Agent2 service
      ansible.builtin.systemd:
        name: zabbix-agent2
        enabled: yes
        state: started

    - name: Open Zabbix Agent port (firewalld)
      ansible.builtin.firewalld:
        port: 10050/tcp
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart Zabbix Agent2
      ansible.builtin.systemd:
        name: zabbix-agent2
        state: restarted
