---
- name: Install Zabbix Agent 2 on Windows
  hosts: windows  # Target your Windows hosts (defined in your AWX inventory)
  gather_facts: no  # Skip gathering facts if not needed for simplicity

  vars:
    msi_path: "C:\\temp\\zabbix_agent-2.7.2.2-windows-amd64-openssl.msi"  # Local path on the Windows host or remote path
    zabbix_server: "zabbix.example.com"  # Replace with your Zabbix server hostname/IP
    zabbix_hostname: "{{ inventory_hostname }}"  # Use the host's inventory name as Zabbix hostname

  tasks:
    - name: Ensure installation directory exists
      ansible.windows.win_file:
        path: "C:\\temp"
        state: directory
      register: dir_result

    - name: Copy Zabbix Agent MSI from repository to Windows host
      ansible.windows.win_copy:
        src: "zabbix_tools/zabbix_agent-2.7.2.2-windows-amd64-openssl.msi"  # Path in your GitHub repo
        dest: "{{ msi_path }}"
      register: copy_result

    - name: Install Zabbix Agent 2 using MSI package
      ansible.windows.win_package:
        path: "{{ msi_path }}"
        state: present
        arguments: >
          /quiet
          ZABBIX_SERVER={{ zabbix_server }}
          ZABBIX_HOSTNAME={{ zabbix_hostname }}
      register: install_result

    - name: Ensure Zabbix Agent service is running
      ansible.windows.win_service:
        name: "Zabbix Agent 2"
        state: started
        start_mode: auto
      register: service_result

    - name: Clean up MSI file after installation
      ansible.windows.win_file:
        path: "{{ msi_path }}"
        state: absent
      when: install_result.changed

  handlers:
    - name: Restart Zabbix Agent 2
      ansible.windows.win_service:
        name: "Zabbix Agent 2"
        state: restarted
