---
- name: Install Zabbix Agent 2 on Windows
  hosts: "{{ target_host | default('all') }}"
  gather_facts: yes
  tasks:
    - name: Create a temporary directory to store the installer
      win_tempfile:
        state: directory
      register: temp_dir

    - name: Download Zabbix Agent 2 installer
      win_get_url:
        url: https://cdn.zabbix.com/zabbix/binaries/stable/7.2/7.2.3/zabbix_agent2-7.2.3-windows-amd64-openssl.msi
        dest: "{{ temp_dir.path }}\\zabbix_agent2.msi"
      when: zabbix_agent2_version is not defined

    - name: Install Zabbix Agent 2
      win_package:
        path: "{{ temp_dir.path }}\\zabbix_agent2.msi"
        product_id: "{Zabbix Agent 2}"
        arguments: /quiet /norestart SERVER={{ zabbix_server }} LISTENPORT=10050 HOSTNAME={{ ansible_hostname }}
      register: install_result

    - name: Ensure Zabbix Agent 2 service is running
      win_service:
        name: Zabbix Agent 2
        state: started
        start_mode: auto

    - name: Clean up temporary directory
      win_file:
        path: "{{ temp_dir.path }}"
        state: absent

    - name: Debug install result
      debug:
        var: install_result
