---
- name: Install Notepad++ using Chocolatey
  hosts: windows
  tasks:
    - name: Install Notepad++
      chocolatey.chocolatey.win_chocolatey:
        name: notepadplusplus
        state: present
