---
- name: Install Notepad++ using Chocolatey
  hosts: all
  collections:
    - chocolatey.chocolatey
  tasks:
    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present
