---
- name: Add host to Zabbix
  hosts: localhost
  connection: local
  vars:
    zabbix_server_url: "{{ zabbix_server_url }}"
    zabbix_login_user: "{{ zabbix_login_user }}"
    zabbix_login_password: "{{ zabbix_login_password }}"
    host_name: "{{ host_name }}"
    host_visible_name: "{{ host_visible_name }}"
    host_description: "{{ host_description }}"
    host_groups: "{{ host_groups }}"
    host_templates: "{{ host_templates }}"
    host_ip: "{{ host_ip }}"
  tasks:
    - name: Add new host to Zabbix
      community.zabbix.zabbix_host:
        server_url: "{{ zabbix_server_url }}"
        login_user: "{{ zabbix_login_user }}"
        login_password: "{{ zabbix_login_password }}"
        host_name: "{{ host_name }}"
        visible_name: "{{ host_visible_name }}"
        description: "{{ host_description }}"
        host_groups: "{{ host_groups }}"
        link_templates: "{{ host_templates }}"
        status: enabled
        state: present
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ host_ip }}"
            dns: ""
            port: 10050
