---
- name: Install Zabbix Agent 2 on Windows
  hosts: all
  tasks:
    - name: Ensure Chocolatey is installed
      chocolatey.chocolatey:
        name: chocolatey
        state: present

    - name: Install Zabbix Agent 2
      chocolatey.chocolatey:
        name: zabbix-agent2
        state: present

    - name: Configure Zabbix Agent 2
      win_ini:
        path: C:\ProgramData\zabbix\zabbix_agentd.conf
        section: "Zabbix"
        option: "Server"
        value: "{{ zabbix_server }}"

    - name: Start Zabbix Agent 2 service
      win_service:
        name: Zabbix Agent 2
        start_mode: auto
        state: started
